import React, { useEffect, useState } from 'react';
import {
  getSections,
  getFacultyList,
  getRooms,
  getGeneratedPeriods,
  getUniversityConfig,
  getGeneratedTimetable
} from '../services/api';
import { CalendarDays, RefreshCw, Info, DoorClosed, Users, BookOpen, FlaskConical } from 'lucide-react';

const ViewTimetable = () => {
  const [viewType, setViewType] = useState('section'); // 'section' | 'faculty' | 'room'
  const [selectedId, setSelectedId] = useState('');

  const [sections, setSections] = useState([]);
  const [facultyList, setFacultyList] = useState([]);
  const [rooms, setRooms] = useState([]);
  const [periods, setPeriods] = useState([]);
  const [workingDays, setWorkingDays] = useState([
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday'
  ]);
  const [timetableEntries, setTimetableEntries] = useState([]);
  const [loading, setLoading] = useState(true);
  const [fetchingEntries, setFetchingEntries] = useState(false);

  // Initial Data Fetch
  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      try {
        const [secRes, facRes, rmRes, pRes, cfgRes] = await Promise.all([
          getSections(),
          getFacultyList(),
          getRooms(),
          getGeneratedPeriods(),
          getUniversityConfig()
        ]);

        setSections(secRes.data || []);
        setFacultyList(facRes.data || []);
        setRooms(rmRes.data || []);
        setPeriods(pRes.data || []);
        if (cfgRes.data?.working_days) {
          setWorkingDays(cfgRes.data.working_days);
        }

        if (secRes.data?.length > 0) {
          setSelectedId(secRes.data[0].id.toString());
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  // Fetch generated entries whenever selection changes
  useEffect(() => {
    if (!selectedId) return;

    const fetchEntries = async () => {
      setFetchingEntries(true);
      try {
        const params = {};
        if (viewType === 'section') params.section_id = selectedId;
        if (viewType === 'faculty') params.faculty_id = selectedId;
        if (viewType === 'room') params.room_id = selectedId;

        const res = await getGeneratedTimetable(params);
        setTimetableEntries(res.data || []);
      } catch (err) {
        console.error(err);
      } finally {
        setFetchingEntries(false);
      }
    };

    fetchEntries();
  }, [viewType, selectedId]);

  const getTargetLabel = () => {
    if (viewType === 'section') {
      const s = sections.find((x) => x.id.toString() === selectedId);
      return s ? `Section ${s.name}` : 'Select Section';
    }
    if (viewType === 'faculty') {
      const f = facultyList.find((x) => x.id.toString() === selectedId);
      return f ? `Faculty: ${f.name}` : 'Select Faculty';
    }
    if (viewType === 'room') {
      const r = rooms.find((x) => x.id.toString() === selectedId);
      return r ? `Room: ${r.room_number} (${r.name})` : 'Select Room';
    }
    return '';
  };

  const findAssignedEntry = (day, periodNum) => {
    return timetableEntries.find(
      (e) => e.day_of_week === day && e.period_number === periodNum
    );
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-12 text-slate-500">
        <RefreshCw className="w-6 h-6 animate-spin mr-2" />
        <span>Loading Timetable View...</span>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Title */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-800">University Timetable Grid Viewer</h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Interactive weekly schedule matrix generated by the Phase 2.1 CSP & Backtracking solver.
          </p>
        </div>

        {/* View Controls */}
        <div className="flex flex-wrap items-center gap-3 bg-white p-2 rounded-xl border border-slate-200 shadow-sm">
          <div className="flex bg-slate-100 p-1 rounded-lg">
            <button
              onClick={() => {
                setViewType('section');
                if (sections.length > 0) setSelectedId(sections[0].id.toString());
              }}
              className={`px-3 py-1 text-xs font-semibold rounded-md transition-all ${
                viewType === 'section' ? 'bg-white text-blue-600 shadow-sm' : 'text-slate-600'
              }`}
            >
              By Section
            </button>
            <button
              onClick={() => {
                setViewType('faculty');
                if (facultyList.length > 0) setSelectedId(facultyList[0].id.toString());
              }}
              className={`px-3 py-1 text-xs font-semibold rounded-md transition-all ${
                viewType === 'faculty' ? 'bg-white text-blue-600 shadow-sm' : 'text-slate-600'
              }`}
            >
              By Faculty
            </button>
            <button
              onClick={() => {
                setViewType('room');
                if (rooms.length > 0) setSelectedId(rooms[0].id.toString());
              }}
              className={`px-3 py-1 text-xs font-semibold rounded-md transition-all ${
                viewType === 'room' ? 'bg-white text-blue-600 shadow-sm' : 'text-slate-600'
              }`}
            >
              By Room
            </button>
          </div>

          <select
            value={selectedId}
            onChange={(e) => setSelectedId(e.target.value)}
            className="px-3 py-1.5 text-xs font-semibold border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none bg-slate-50"
          >
            {viewType === 'section' &&
              sections.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name} ({s.department_name})
                </option>
              ))}
            {viewType === 'faculty' &&
              facultyList.map((f) => (
                <option key={f.id} value={f.id}>
                  {f.name} ({f.department_name})
                </option>
              ))}
            {viewType === 'room' &&
              rooms.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.room_number} - {r.name}
                </option>
              ))}
          </select>
        </div>
      </div>

      {/* Grid Header Card */}
      <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <h3 className="text-base font-bold text-slate-800 flex items-center space-x-2">
            <CalendarDays className="w-5 h-5 text-blue-600" />
            <span>{getTargetLabel()} - Weekly Master Schedule</span>
          </h3>
          {fetchingEntries ? (
            <span className="text-xs text-slate-400 flex items-center space-x-1">
              <RefreshCw className="w-3.5 h-3.5 animate-spin" />
              <span>Fetching...</span>
            </span>
          ) : (
            <span className="px-3 py-1 bg-emerald-50 text-emerald-700 text-xs font-semibold rounded-full border border-emerald-200">
              {timetableEntries.length} Assigned Slots
            </span>
          )}
        </div>

        {/* Timetable Grid Table */}
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse min-w-[850px]">
            <thead>
              <tr className="bg-slate-800 text-white font-semibold uppercase tracking-wider">
                <th className="py-3 px-3 w-28 border-r border-slate-700">Day / Period</th>
                {periods.map((p, idx) => (
                  <th key={idx} className="py-3 px-3 text-center border-r border-slate-700">
                    <div>{p.label}</div>
                    <div className="text-[10px] font-mono text-slate-300 font-normal">
                      {p.start_time} - {p.end_time}
                    </div>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 text-slate-700">
              {workingDays.map((day) => (
                <tr key={day} className="hover:bg-slate-50/50">
                  <td className="py-3 px-3 font-bold bg-slate-50 border-r border-slate-200 text-slate-800">
                    {day}
                  </td>
                  {periods.map((p, idx) => {
                    const isMorningBreak = p.period_type === 'MorningBreak';
                    const isLunchBreak = p.period_type === 'LunchBreak';

                    if (isMorningBreak) {
                      return (
                        <td
                          key={idx}
                          className="py-3 px-2 text-center bg-amber-50 text-amber-900 font-bold border-r border-slate-200 text-[11px]"
                        >
                          Morning Break
                        </td>
                      );
                    }

                    if (isLunchBreak) {
                      return (
                        <td
                          key={idx}
                          className="py-3 px-2 text-center bg-indigo-50 text-indigo-900 font-bold border-r border-slate-200 text-[11px]"
                        >
                          Lunch Break
                        </td>
                      );
                    }

                    const entry = findAssignedEntry(day, p.period_number);

                    if (!entry) {
                      return (
                        <td
                          key={idx}
                          className="py-3 px-2 text-center border-r border-slate-200 bg-slate-50/40 text-slate-400 italic text-[11px]"
                        >
                          Free Slot
                        </td>
                      );
                    }

                    const isLab = entry.course_type === 'Lab';

                    return (
                      <td
                        key={idx}
                        className={`p-2 border-r border-slate-200 transition-colors ${
                          isLab ? 'bg-amber-50/80 border-l-4 border-l-amber-500' : 'bg-blue-50/80 border-l-4 border-l-blue-500'
                        }`}
                      >
                        <div className="space-y-0.5 text-left">
                          <div className="font-extrabold text-slate-900 text-xs flex items-center justify-between">
                            <span>{entry.subject_code}</span>
                            {isLab && (
                              <span className="px-1.5 py-0.2 bg-amber-200 text-amber-900 rounded text-[9px] font-bold">
                                LAB
                              </span>
                            )}
                          </div>
                          <div className="text-[10px] text-slate-700 font-semibold truncate" title={entry.subject_name}>
                            {entry.subject_name}
                          </div>
                          
                          <div className="pt-1 text-[10px] text-slate-600 space-y-0.5 border-t border-slate-200/60 mt-1">
                            {viewType !== 'section' && (
                              <div className="flex items-center space-x-1 font-bold text-slate-800">
                                <span>Sec: {entry.section_name}</span>
                              </div>
                            )}
                            {viewType !== 'faculty' && (
                              <div className="flex items-center space-x-1 text-slate-700">
                                <Users className="w-3 h-3 text-purple-600 shrink-0" />
                                <span className="truncate">{entry.faculty_name}</span>
                              </div>
                            )}
                            {viewType !== 'room' && (
                              <div className="flex items-center space-x-1 text-slate-700">
                                <DoorClosed className="w-3 h-3 text-teal-600 shrink-0" />
                                <span>{entry.room_number}</span>
                              </div>
                            )}
                          </div>
                        </div>
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default ViewTimetable;
